st2:
  image: stackstorm/stackstorm:latest
  container_name: st2
  hostname: st2
  env_file:
    - conf/st2.env
    - conf/rmq.env
  ports:
    - "443:443"
  volumes:
    - ./packs.dev:/opt/stackstorm/packs.dev
  links:
    - mongo
    - rabbitmq

mongo:
  image: mongo:3.4
  container_name: mongodb
  hostname: mongodb
  expose:
    - "27017"

rabbitmq:
  image: rabbitmq:management
  container_name: rabbitmq
  hostname: rabbitmq
  env_file:
    - conf/rmq.env
  expose:
    - "5672"
