version: '3'

services:
  stackstorm:
    image: stackstorm/stackstorm:latest
    container_name: stackstorm
    build:
      context: images/stackstorm
    env_file:
      - conf/st2.env
      - conf/rmq.env
    ports:
      - "443:443"
    networks:
      - public
      - private
    volumes:
      - ./packs.dev:/opt/stackstorm/packs.dev
  mongo:
    image: mongo:3.4
    container_name: mongo
    networks:
      - private
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - conf/rmq.env
    networks:
      - private

#  postgres:
#    image: postgres:latest
#    networks:
#      - private
#  redis:
#    image: redis:latest
#    networks:
#      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
