#
# docker compose file for optional chatops service
#
# to enable this, set
#  COMPOSE_FILE=docker-compose.yml:docker-compose-chatops.yml
# in your shell environment or in an `.env` file in this directory
#
version: '3'

services:
    st2chatops:
        image: ${ST2_IMAGE_REPO:-stackstorm/}st2chatops:${ST2_VERSION:-3.3.0}
        restart: on-failure
        depends_on:
            - st2api
            - st2auth
            - st2stream
        command: /st2chatops-startup.sh
        networks:
            - private
        environment:
            ST2_AUTH_URL: ${ST2_AUTH_URL:-http://st2auth:9100/}
            ST2_API_URL: ${ST2_API_URL:-http://st2api:9101/}
            ST2_STREAM_URL: ${ST2_STREAM_URL:-http://st2stream:9102/}
            ST2_API_KEY: ${ST2_API_KEY:-change-to-your-st2-api-key}
            HUBOT_ADAPTER: ${HUBOT_ADAPTER:-slack}
            HUBOT_LOG_LEVEL: ${HUBOT_LOG_LEVEL:-debug}
            HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN:-xoxb-CHANGE-ME-PLEASE}
            TZ: ${TZ:-UTC}
        volumes:
            - ./files/st2chatops.env:/opt/stackstorm/chatops/st2chatops.env:ro
            - ./scripts/st2chatops-startup.sh:/st2chatops-startup.sh
        dns_search: .
