st2-upstart:
  image: st2-upstart:latest
  expose:
    - "22"
    - "80"
    - "443"
  ports:
    - "22:22"
  volumes:
    - ./packs:/opt/stackstorm/packs
  links:
    - mongo
    - rabbitmq

mongo:
  image: mongo:3.4
  expose:
    - "27017"

rabbitmq:
  image: rabbitmq:management
  environment:
    - "RABBITMQ_DEFAULT_USER=admin"
    - "RABBITMQ_DEFAULT_PASS=pwd123"
  hostname: rabbitmq
  expose:
    - "5672"

postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=mistral-user"
    - "POSTGRES_PASSWORD=mistral-pass"
    - "POSTGRES_DB=mistral"
  expose:
    - "5432"
