st2:
  image: st2-upstart:latest
  container_name: st2
  hostname: st2
  environment:
    - ST2_USER
    - ST2_PASSWORD
  command: [$ST2_USER,$ST2_PASSWORD]
  expose:
    - "22"
    - "80"
    - "443"
  volumes:
    - ./packs.dev:/opt/stackstorm/packs.dev
  links:
    - mongo
    - rabbitmq

mongo:
  image: mongo:3.4
  container_name: mongodb
  hostname: mongodb
  expose:
    - "27017"

rabbitmq:
  image: rabbitmq:management
  container_name: rabbitmq
  hostname: rabbitmq
  env_file:
    - conf/dev.env
  environment:
    - "RABBITMQ_DEFAULT_USER=admin"
    - "RABBITMQ_DEFAULT_PASS=pwd123"
  expose:
    - "5672"
