version: 2.1
jobs:
  # Verify docker-compose.yml format for any immediate linting issues
  docker-compose-lint:
    docker:
      - image: docker/compose:latest
    steps:
      - checkout
      - run:
          name: Docker-compose lint check
          command: docker-compose config

  # Run docker-compose install and verify st2 deployment
  docker-compose-up:
    working_directory: ~/docker
    machine:
      # Available images https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Pull Docker Images
          command: docker-compose pull
      - run:
          name: Start st2 with docker-compose
          command: docker-compose up --detach
      - run:
          name: Run st2 smoke-tests
          command: |
            sleep 60
            docker-compose -f tests/st2tests.yaml up
      - run:
          when: on_fail
          name: Troubleshooting the build failure
          command: |
            docker-compose ps
            # Display logs to help troubleshoot build failures, etc
            docker-compose logs --tail="500" st2api


workflows:
  version: 2
  docker-compose:
    jobs:
      - docker-compose-lint
      - docker-compose-up:
          requires:
            - docker-compose-lint

  # Nightly run docker-compose install and ensure no regressions for st2 deployment in 'master' branch
  docker-compose-nightly:
    jobs:
      - docker-compose-lint
      - docker-compose-up:
          requires:
            - docker-compose-lint
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
